### ISSUE TITLE
Scavenger can't locate token

### ISSUE THREAD

**Issue by cemiu** [Emzi0767/Discord-Emoji-Scavenger#2]
When running the scavenger I get the following output

```
Beginning quick scavenge
Beginning run
Locating Discord token

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at EmoteScavenger.Program.Main(String[] args) in C:\Users\Mateusz\Documents\Visual Studio 2017\Projects\EmoteScavenger\EmoteScavenger\Program.cs:line 26
```

I tried to delete the content of the "%appdata%\discord\Local Storage" folder and restart discord but it still didn't work.

Additional note: I have Discord Stable, PTB and Canary installed

**Comment by Emzi0767** [comment]
If you delete local storage, you're deleting the token.

**Comment by cemiu** [comment]
I deleted local storage, reinstalled Discord and logged back in. The folder reappeared with the token inside.

The token was there before I removed the folder and after it reappeared but the scavenger failed to recognize it. Both times I received the same error message.

**Comment by Emzi0767** [comment]
What Windows version

**Comment by cemiu** [comment]
Windows 10, x64, build 16299

**Comment by Emzi0767** [comment]
And what's the scavenger version?

**Comment by cemiu** [comment]
I used v1.0.2 from the release tab.

**Comment by Emzi0767** [comment]
Strange, because the stack trace points to a line where no nullref can occur (static call). Are you absolutely sure it's 1.0.2?

**Comment by cemiu** [comment]
I just tried redownloading the 1.0.2 build and got the same error message. Both commits to Program.cs have the exact same line 26 so I would likely get the same error for every build.

Edit: just tried it out. Same output from version 1.0.0, 1.0.1 and 1.0.2

**Comment by ghost** [comment]
I have the same problem

**Comment by Emzi0767** [comment]
Since I decided to drop support altogether, I'm closing this. People can investigate and fix issues themselves, however I'm not going to aid in that.
