### ISSUE TITLE
Scavenger not working

### ISSUE THREAD

**Issue by ghost** [Emzi0767/Discord-Emoji-Scavenger#4]
Beginning quick scavenge
Beginning run
Locating Discord token

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at EmoteScavenger.Program.Main(String[] args) in C:\Users\Mateusz\Documents\Visual Studio 2017\Projects\EmoteScavenger\EmoteScavenger\Program.cs:line 26

**Comment by Emzi0767** [comment]
I'm not really providing support for it, especially since it's very much in violation of terms of service to use it.

You can investigate and fix the problem on your own, I don't intend to do anything about it.
